# Generated by Django 5.1.3 on 2024-11-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
